<!DOCTYPE html><html lang="pt-BR"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#0756b9">
<meta name="description" content="{{ $metaDescription }}">
<link rel="canonical" href="{{ $canonicalUrl }}">
<title>{{ $pageTitle }}</title><script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'WebSite','name'=>'Futebol na TV','url'=>route('home'),'description'=>'Guia de jogos de futebol na TV e no streaming no Brasil.'], JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) !!}</script>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-[#f4f7fb] text-slate-950 antialiased">
@include('partials.site-header')
<main><section class="hero-panel border-b border-blue-100"><div class="mx-auto max-w-6xl px-4 pb-16 pt-11 sm:px-6"><div class="max-w-3xl">
<p class="mb-4 inline-flex rounded-full border border-blue-200 bg-white/80 px-3 py-1.5 text-xs font-extrabold uppercase tracking-widest text-blue-700">Programação por data</p>
<h1 class="text-4xl font-black tracking-[-.045em] sm:text-5xl">{{ $pageHeading }}</h1>
<p class="mt-4 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg">Todos os jogos com transmissão confirmada para o Brasil, organizados por campeonato e canal.</p>
</div></div></section>
<div class="mx-auto max-w-6xl px-4 pb-14 sm:px-6">
<nav class="date-nav -mt-7 mb-9 grid gap-3 rounded-2xl border border-white bg-white p-3 shadow-xl shadow-slate-900/[.07] sm:grid-cols-[1fr_auto_1fr] sm:items-center sm:p-4" aria-label="Navegação por data">
<a class="date-link sm:justify-start" href="{{ $previousDateUrl }}">‹ <span>Dia anterior</span></a>
<form method="get" action="{{ route('fixtures.redirect-to-date') }}" class="date-form flex min-w-0 items-center gap-2 rounded-xl bg-slate-50 p-1.5 ring-1 ring-slate-200"><label for="data" class="sr-only">Escolher data</label><span class="pl-2 text-blue-600">▣</span><input id="data" name="data" type="date" value="{{ $selectedDate->format('Y-m-d') }}" class="min-w-0 flex-1 bg-transparent px-1 py-2 text-sm font-bold outline-none sm:w-36"><button class="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-extrabold text-white shadow-md shadow-blue-600/20 hover:bg-blue-700">Ver</button></form>
<a class="date-link sm:justify-end" href="{{ $nextDateUrl }}"><span>Próximo dia</span> ›</a></nav>
@if($isToday)
<aside class="mb-7 flex flex-col gap-3 rounded-2xl border border-blue-200 bg-gradient-to-r from-blue-50 to-white px-5 py-4 shadow-sm sm:flex-row sm:items-center sm:justify-between" aria-label="Destaque da próxima programação">
<div><p class="text-xs font-extrabold uppercase tracking-widest text-blue-600">Próxima programação</p><p class="mt-1 font-bold text-slate-600">Antecipe-se e confira as partidas televisionadas do próximo dia.</p></div>
<a href="{{ route('fixtures.tomorrow') }}" class="inline-flex shrink-0 items-center justify-center rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white shadow-md shadow-blue-600/20 transition hover:bg-blue-700">Jogos de amanhã na TV <span class="ml-2">→</span></a>
</aside>
@endif
@unless($isToday)<div class="mb-6 text-center"><a href="{{ route('home') }}" class="text-sm font-extrabold text-blue-700">Voltar aos jogos de hoje</a></div>@endunless
<section aria-labelledby="selected-date"><div class="mb-5 flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-blue-100 text-blue-700">▣</span><div><p class="text-xs font-bold uppercase tracking-widest text-slate-400">Agenda do dia</p><h2 id="selected-date" class="text-lg font-black capitalize tracking-tight sm:text-xl">{{ $selectedDate->translatedFormat('l, d \\d\\e F \\d\\e Y') }}</h2></div></div>
@if($fixturesByCompetition->isNotEmpty())<div class="space-y-5">@foreach($fixturesByCompetition as $leagueFixtures) @php($competition=$leagueFixtures->first()->competition)
<section class="league-card overflow-hidden rounded-2xl border border-slate-200/80 bg-white" aria-labelledby="competition-{{ $competition->id }}">
<header class="flex items-center gap-3 border-b border-slate-100 bg-slate-50/70 px-4 py-3.5 sm:px-5"><a href="{{ $competition->publicUrl() }}" class="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-slate-200 bg-white shadow-sm">@if($competition->logoSource())<img src="{{ $competition->logoSource() }}" alt="Logo {{ $competition->name }}" class="h-7 w-7 object-contain">@endif</a><h3 id="competition-{{ $competition->id }}" class="min-w-0 truncate font-black"><a href="{{ $competition->publicUrl() }}" class="hover:text-blue-700 hover:underline">{{ $competition->name }}</a></h3><span class="ml-auto shrink-0 rounded-full bg-blue-50 px-3 py-1 text-xs font-extrabold text-blue-700">{{ $leagueFixtures->count() }} {{ $leagueFixtures->count()===1?'jogo':'jogos' }}</span></header>
<div class="divide-y divide-slate-100">@foreach($leagueFixtures as $fixture)<article class="fixture-row relative grid gap-4 px-4 py-4 sm:grid-cols-[5.5rem_minmax(0,1fr)_minmax(12rem,auto)] sm:items-center sm:px-5">
<a href="{{ $fixture->publicUrl() }}" class="absolute inset-0 z-10" aria-label="Ver detalhes de {{ $fixture->homeTeam->name }} x {{ $fixture->awayTeam->name }}"></a>
<time datetime="{{ $fixture->starts_at->toIso8601String() }}" class="flex items-center gap-2 text-xl font-black text-blue-700 sm:border-r sm:border-slate-100 sm:py-2"><i class="h-8 w-1 rounded-full bg-blue-500"></i>{{ $fixture->starts_at->format('H:i') }}</time>
<div class="space-y-2.5">@foreach([$fixture->homeTeam,$fixture->awayTeam] as $team)<a href="{{ $team->publicUrl() }}" class="relative z-20 flex min-w-0 items-center gap-3 font-bold text-slate-800 hover:text-blue-700 hover:underline"><span class="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-slate-50">@if($team->logoSource())<img src="{{ $team->logoSource() }}" alt="Escudo {{ $team->name }}" class="h-7 w-7 object-contain" loading="lazy">@endif</span><span class="truncate">{{ $team->name }}</span></a>@endforeach</div>
<div class="flex flex-wrap gap-2 sm:justify-end">@foreach($fixture->channels as $channel)<a href="{{ $channel->publicUrl() }}" class="channel-pill relative z-20 inline-flex items-center gap-2 rounded-xl bg-blue-50 px-3 py-2 text-xs font-extrabold text-blue-800 hover:bg-blue-100 hover:underline"><span>▻</span>{{ $channel->name }}</a>@endforeach</div>
</article>@endforeach</div></section>@endforeach</div>
@else<div class="rounded-2xl border border-slate-200 bg-white p-10 text-center shadow-sm"><span class="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-blue-50 text-blue-600">@include('partials.ball-icon')</span><h2 class="mt-4 text-xl font-black">Nenhum jogo na TV nesta data</h2><p class="mt-2 text-slate-600">Ainda não há partidas com transmissão informada para este dia.</p></div>@endif</section>
<section class="mt-12 overflow-hidden rounded-3xl border border-blue-100 bg-white shadow-lg shadow-slate-900/[.04]" aria-labelledby="guia-futebol-tv"><div class="bg-gradient-to-r from-blue-700 to-blue-500 px-6 py-8 text-white sm:px-9"><p class="text-xs font-extrabold uppercase tracking-[.16em] text-blue-100">Seu guia de transmissões</p><h2 id="guia-futebol-tv" class="mt-2 max-w-3xl text-3xl font-black tracking-[-.04em] sm:text-4xl">Futebol na TV: saiba onde assistir aos jogos de {{ $seoDayLabel }}</h2><p class="mt-4 max-w-3xl leading-7 text-blue-50">O Futebol na TV reúne em um só lugar a programação de partidas transmitidas ao vivo no Brasil. Consulte horários, campeonatos, times e canais para organizar seu dia e não perder nenhum jogo.</p></div>
<div class="grid gap-8 px-6 py-8 sm:px-9 lg:grid-cols-2 lg:gap-10"><div><h3 class="text-xl font-black text-slate-900">Jogos na TV e no streaming</h3><p class="mt-3 leading-7 text-slate-600">Nossa agenda inclui jogos exibidos na televisão aberta, TV por assinatura, canais esportivos e plataformas de streaming. Cada partida informa onde assistir, o horário de Brasília e a competição relacionada.</p><p class="mt-4 leading-7 text-slate-600">Você também pode navegar pelos <a href="{{ route('teams.index') }}" class="font-bold text-blue-700 hover:underline">times de futebol</a> ou consultar a programação organizada por <a href="{{ route('channels.index') }}" class="font-bold text-blue-700 hover:underline">canais de transmissão</a>.</p></div><div><h3 class="text-xl font-black text-slate-900">Como encontrar onde assistir futebol ao vivo?</h3><p class="mt-3 leading-7 text-slate-600">Use o seletor de datas para ver os jogos de hoje, de amanhã ou de qualquer outro dia disponível. As partidas ficam agrupadas por campeonato, facilitando a busca por futebol brasileiro, torneios internacionais e outras competições.</p><p class="mt-4 leading-7 text-slate-600">Ao abrir um jogo, você encontra um resumo com os times, data, horário e todos os canais informados para a transmissão.</p></div></div>
<div class="grid border-t border-slate-100 bg-slate-50/70 sm:grid-cols-3"><div class="p-6 sm:border-r sm:border-slate-200"><h3 class="font-black text-slate-900">A programação é atualizada?</h3><p class="mt-2 text-sm leading-6 text-slate-600">Sim. Nossa base é sincronizada regularmente para acompanhar novos jogos e mudanças nos canais.</p></div><div class="border-t border-slate-200 p-6 sm:border-r sm:border-t-0"><h3 class="font-black text-slate-900">Os horários são de Brasília?</h3><p class="mt-2 text-sm leading-6 text-slate-600">Sim. Todos os horários publicados no guia seguem o fuso oficial de Brasília.</p></div><div class="border-t border-slate-200 p-6 sm:border-t-0"><h3 class="font-black text-slate-900">O site transmite os jogos?</h3><p class="mt-2 text-sm leading-6 text-slate-600">Não. Somos um guia informativo e indicamos as emissoras ou plataformas responsáveis pela transmissão.</p></div></div></section>
<div class="mt-10 border-t border-slate-200 pt-6 text-sm text-slate-500">Horários de Brasília. A programação pode sofrer alterações.</div>
</div></main>@include('partials.legal-footer')</body></html>
