[program:futebolnatv-push-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/nice -n 10 /usr/bin/php /var/www/futebolnatv/artisan queue:work redis_push --queue=push --sleep=1 --tries=3 --timeout=180 --max-time=3600
directory=/var/www/futebolnatv
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/futebolnatv/storage/logs/push-worker.log
stopwaitsecs=210
