<!DOCTYPE html>
<html lang="pt-BR">
<head>@include('partials.google-tag-head')<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Notificações Push | Administração</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-[#f4f7fb] text-slate-950">@include('partials.google-tag-body')
<header class="bg-slate-950 text-white"><div class="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-4 py-4 sm:px-6"><div><strong class="block text-lg font-black">Futebol na TV</strong><small class="text-slate-400">Administração</small></div><nav class="flex flex-wrap items-center gap-1 text-sm font-bold"><a href="{{ route('admin.channels.index') }}" class="rounded-lg px-3 py-2 hover:bg-white/10">Canais</a><a href="{{ route('admin.competitions.index') }}" class="rounded-lg px-3 py-2 hover:bg-white/10">Campeonatos</a><a href="{{ route('admin.pwa-installations.index') }}" class="rounded-lg px-3 py-2 hover:bg-white/10">Instalações PWA</a><a href="{{ route('admin.push.index') }}" class="rounded-lg bg-white/10 px-3 py-2">Push</a><form method="post" action="{{ route('admin.logout') }}">@csrf<button class="rounded-lg px-3 py-2 hover:bg-white/10">Sair</button></form></nav></div></header>
<main class="mx-auto max-w-6xl px-4 py-8 sm:px-6">
    <div class="mb-7"><p class="text-xs font-extrabold uppercase tracking-widest text-blue-700">Comunicação direta</p><h1 class="mt-1 text-3xl font-black">Notificações Push</h1><p class="mt-2 text-slate-500">Envios manuais e acompanhamento dos alertas automáticos.</p></div>
    @if(session('status'))<div class="mb-5 rounded-xl bg-emerald-50 px-4 py-3 font-bold text-emerald-800">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="mb-5 rounded-xl bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{{ $errors->first() }}</div>@endif
    <section class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        @foreach([['Inscritos',$metrics['subscribers'],'text-blue-700'],['Resumo diário',$metrics['daily'],'text-cyan-600'],['Lembretes',$metrics['reminders'],'text-violet-600'],['Entregas iniciadas',$metrics['sent'],'text-emerald-600']] as [$label,$value,$color])
            <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-extrabold uppercase tracking-wider text-slate-400">{{ $label }}</p><strong class="mt-2 block text-3xl font-black {{ $color }}">{{ number_format($value,0,',','.') }}</strong></article>
        @endforeach
    </section>
    <div class="mt-7 grid gap-6 lg:grid-cols-[1fr_1.25fr]">
        <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black">Enviar notificação</h2><p class="mt-1 text-sm text-slate-500">A mensagem entra na fila e é enviada em segundo plano, sem deixar o site lento.</p><form method="post" action="{{ route('admin.push.store') }}" enctype="multipart/form-data" class="mt-5 space-y-4">@csrf<div><label for="push-title" class="mb-1.5 block text-sm font-bold">Título</label><input id="push-title" name="title" value="{{ old('title') }}" maxlength="80" required class="w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-blue-500" placeholder="Principais jogos de hoje"></div><div><label for="push-body" class="mb-1.5 block text-sm font-bold">Mensagem</label><textarea id="push-body" name="body" maxlength="180" required rows="3" class="w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-blue-500" placeholder="Confira horários e onde assistir.">{{ old('body') }}</textarea></div><div><label for="push-url" class="mb-1.5 block text-sm font-bold">Página de destino</label><input id="push-url" name="target_url" value="{{ old('target_url',route('home')) }}" class="w-full rounded-xl border border-slate-300 px-4 py-3 text-sm outline-none focus:border-blue-500"></div><div class="grid gap-4 sm:grid-cols-2"><div><label for="push-icon" class="mb-1.5 block text-sm font-bold">Ícone <span class="font-normal text-slate-400">(opcional)</span></label><input id="push-icon" name="icon" type="file" accept="image/png,image/jpeg,image/webp" class="block w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-xs file:mr-3 file:rounded-lg file:border-0 file:bg-blue-50 file:px-3 file:py-2 file:font-bold file:text-blue-700"><p class="mt-1.5 text-xs leading-5 text-slate-400">Formato quadrado é recomendado, até 1 MB. Sem arquivo, usa a marca do site.</p></div><div><label for="push-image" class="mb-1.5 block text-sm font-bold">Imagem de destaque <span class="font-normal text-slate-400">(opcional)</span></label><input id="push-image" name="image" type="file" accept="image/png,image/jpeg,image/webp" class="block w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-xs file:mr-3 file:rounded-lg file:border-0 file:bg-blue-50 file:px-3 file:py-2 file:font-bold file:text-blue-700"><p class="mt-1.5 text-xs leading-5 text-slate-400">1200 × 630 px é recomendado, até 3 MB. Outras dimensões são aceitas.</p></div></div><div><label for="push-audience" class="mb-1.5 block text-sm font-bold">Público</label><select id="push-audience" name="audience" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3"><option value="all">Todos os inscritos</option><option value="daily">Resumo diário ativado</option><option value="reminders">Lembretes ativados</option></select></div><button class="w-full rounded-xl bg-blue-600 px-5 py-3 font-extrabold text-white hover:bg-blue-700">Adicionar à fila</button></form></section>
        <div class="space-y-6"><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-black">Inscritos por plataforma</h2><div class="mt-3 flex flex-wrap gap-2">@forelse($platforms as $platform)<span class="rounded-full bg-blue-50 px-3 py-1.5 text-sm font-bold capitalize text-blue-700">{{ $platform->platform }} · {{ $platform->total }}</span>@empty<span class="text-sm text-slate-500">Nenhum dispositivo inscrito ainda.</span>@endforelse</div></section><section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="text-lg font-black">Últimos envios</h2></div><div class="divide-y divide-slate-100">@forelse($logs as $log)@php
            [$statusLabel, $statusClass] = match ($log->status) {
                'sent' => ['Enviado', 'bg-emerald-50 text-emerald-700'],
                'processing' => ['Enviando', 'bg-cyan-50 text-cyan-700'],
                'failed' => ['Falhou', 'bg-red-50 text-red-700'],
                default => ['Na fila', 'bg-amber-50 text-amber-700'],
            };
        @endphp<article class="px-5 py-4">@if($log->imageUrl())<img src="{{ $log->imageUrl() }}" alt="" class="mb-3 aspect-[40/21] w-full rounded-xl object-cover" loading="lazy">@endif<div class="flex items-start justify-between gap-3"><div class="flex min-w-0 items-start gap-3">@if($log->iconUrl())<img src="{{ $log->iconUrl() }}" alt="" class="h-10 w-10 shrink-0 rounded-lg object-cover">@endif<div><strong class="block">{{ $log->title }}</strong><p class="mt-1 text-sm text-slate-500">{{ $log->body }}</p></div></div><div class="flex shrink-0 flex-col items-end gap-1.5"><span class="rounded-full px-2.5 py-1 text-xs font-extrabold {{ $statusClass }}">{{ $statusLabel }}</span><span class="text-xs font-bold text-slate-400">{{ $log->type }}</span></div></div><p class="mt-2 text-xs font-bold text-slate-400">@if($log->status === 'sent'){{ $log->recipients_count }} enviados · {{ $log->failed_count }} falhas @elseif($log->status === 'processing')Envio em andamento @elseif($log->status === 'failed')Falha no processamento @elseAguardando processamento @endif· {{ $log->created_at->format('d/m H:i') }}</p></article>@empty<p class="px-5 py-8 text-sm text-slate-500">Nenhuma notificação enviada.</p>@endforelse</div></section></div>
    </div>
</main></body></html>
