@php($description='Veja a programação de futebol no '.$channel->name.', com próximos jogos ao vivo, horários, campeonatos e as últimas 10 partidas transmitidas.')
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Jogos no {{ $channel->name }}: programação de futebol ao vivo | Futebol na TV</title><meta name="description" content="{{ $description }}"><link rel="canonical" href="{{ $channel->publicUrl() }}"><meta property="og:type" content="website"><meta property="og:title" content="Jogos no {{ $channel->name }}"><meta property="og:description" content="{{ $description }}"><meta property="og:url" content="{{ $channel->publicUrl() }}">@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-[#f4f7fb] text-slate-950 antialiased">@include('partials.site-header')
<main class="mx-auto max-w-5xl px-4 py-8 sm:px-6 sm:py-12">
<nav class="mb-7 text-sm font-bold text-blue-700"><a href="{{ route('home') }}">Início</a> <span class="mx-2 text-slate-300">/</span> <a href="{{ route('channels.index') }}">Canais</a> <span class="mx-2 text-slate-300">/</span> {{ $channel->name }}</nav>
<header class="mb-9 flex items-center gap-5 rounded-3xl border border-blue-100 bg-white p-6 shadow-lg shadow-slate-900/[.05] sm:p-8"><span class="grid h-20 w-20 shrink-0 place-items-center rounded-2xl bg-blue-50 text-3xl text-blue-700 sm:h-28 sm:w-28">@if($channel->logoSource())<img src="{{ $channel->logoSource() }}" alt="Logo {{ $channel->name }}" class="object-contain">@else ▶ @endif</span><div><p class="text-xs font-extrabold uppercase tracking-widest text-blue-700">Programação do canal</p><h1 class="mt-2 text-3xl font-black tracking-[-.04em] sm:text-5xl">Jogos no {{ $channel->name }}</h1><p class="mt-3 text-slate-600">Futebol ao vivo, datas e horários de Brasília.</p>@if($channel->external_url)<a href="{{ $channel->external_url }}" target="_blank" rel="nofollow sponsored noopener" class="mt-4 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-extrabold text-white shadow-md hover:bg-blue-700">Acessar {{ $channel->name }} <span>↗</span></a>@endif</div></header>
<div class="space-y-8"><section><div class="mb-4 flex items-end justify-between"><div><p class="text-xs font-bold uppercase tracking-widest text-blue-600">Agenda</p><h2 class="text-2xl font-black">Próximos jogos</h2></div><span class="text-sm font-bold text-slate-400">{{ $upcomingFixtures->count() }} partidas</span></div>@if($upcomingFixtures->isNotEmpty())<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">@foreach($upcomingFixtures as $item)@include('partials.team-fixture')@endforeach</div>@else<div class="rounded-2xl border border-slate-200 bg-white p-7 text-slate-600">Nenhum próximo jogo informado para este canal.</div>@endif</section>
<section><p class="text-xs font-bold uppercase tracking-widest text-slate-400">Histórico recente</p><h2 class="mb-4 text-2xl font-black">Últimos jogos transmitidos</h2>@if($pastFixtures->isNotEmpty())<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">@foreach($pastFixtures as $item)@include('partials.team-fixture')@endforeach</div>@else<div class="rounded-2xl border border-slate-200 bg-white p-7 text-slate-600">Ainda não há transmissões anteriores registradas.</div>@endif</section></div>
<section class="mt-8 rounded-2xl border border-slate-200 bg-white p-6 sm:p-8"><h2 class="text-xl font-black">Programação de futebol no {{ $channel->name }}</h2><p class="mt-3 leading-7 text-slate-600">Esta página reúne os jogos com transmissão informada no {{ $channel->name }}. Acompanhe os próximos confrontos, horários de Brasília e campeonatos. A grade pode ser alterada pelo canal sem aviso prévio.</p></section>
</main>@include('partials.legal-footer')</body></html>
