<!DOCTYPE html>
<html lang="pt-BR">
<head>@include('partials.google-tag-head')<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Instalações PWA | Administração</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-[#f4f7fb] text-slate-950">@include('partials.google-tag-body')
<header class="bg-slate-950 text-white"><div class="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-4 py-4 sm:px-6"><div><strong class="block text-lg font-black">Futebol na TV</strong><small class="text-slate-400">Administração</small></div><nav class="flex flex-wrap items-center gap-1 text-sm font-bold"><a href="{{ route('admin.channels.index') }}" class="rounded-lg px-3 py-2 hover:bg-white/10">Canais</a><a href="{{ route('admin.competitions.index') }}" class="rounded-lg px-3 py-2 hover:bg-white/10">Campeonatos</a><a href="{{ route('admin.pwa-installations.index') }}" class="rounded-lg bg-white/10 px-3 py-2">Instalações PWA</a><form method="post" action="{{ route('admin.logout') }}">@csrf<button class="rounded-lg px-3 py-2 hover:bg-white/10">Sair</button></form></nav></div></header>
<main class="mx-auto max-w-6xl px-4 py-8 sm:px-6">
    <div class="mb-7"><p class="text-xs font-extrabold uppercase tracking-widest text-blue-700">Aplicativo instalável</p><h1 class="mt-1 text-3xl font-black">Instalações do PWA</h1><p class="mt-2 text-slate-500">Acompanhamento anônimo dos dispositivos que instalaram o Futebol na TV.</p></div>
    <section class="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
        @foreach([['Total instalado',$metrics['total'],'text-blue-700'],['Hoje',$metrics['today'],'text-emerald-600'],['Últimos 7 dias',$metrics['sevenDays'],'text-violet-600'],['Últimos 30 dias',$metrics['thirtyDays'],'text-cyan-600'],['Interesse no iPhone',$metrics['interests'],'text-amber-600']] as [$label,$value,$color])
            <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-extrabold uppercase tracking-wider text-slate-400">{{ $label }}</p><strong class="mt-2 block text-3xl font-black {{ $color }}">{{ number_format($value,0,',','.') }}</strong></article>
        @endforeach
    </section>
    <div class="mt-7 grid gap-6 lg:grid-cols-[1.5fr_1fr]">
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-black">Instalações nos últimos 14 dias</h2><div class="mt-6 flex h-52 items-end gap-2">@php($max=max(1,$daily->max('total')))@foreach($daily as $day)<div class="flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><span class="text-xs font-black text-blue-700">{{ $day['total'] ?: '' }}</span><div class="w-full rounded-t-lg bg-gradient-to-t from-blue-700 to-blue-400" style="height:{{ max(4,round(($day['total']/$max)*150)) }}px"></div><small class="whitespace-nowrap text-[10px] font-bold text-slate-400">{{ $day['label'] }}</small></div>@endforeach</div></section>
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-black">Por plataforma</h2><div class="mt-4 divide-y divide-slate-100">@forelse($platforms as $platform)<div class="flex items-center justify-between py-3"><span class="font-bold capitalize text-slate-600">{{ $platform->platform }}</span><strong class="rounded-full bg-blue-50 px-3 py-1 text-blue-700">{{ $platform->total }}</strong></div>@empty<p class="py-6 text-sm text-slate-500">As instalações começarão a aparecer aqui.</p>@endforelse</div></section>
    </div>
    <p class="mt-5 text-xs leading-5 text-slate-400">O Safari no iPhone não informa ao site quando a instalação manual foi concluída. Por isso, cliques nas instruções do iPhone aparecem separadamente como interesse, sem serem somados ao total instalado.</p>
</main></body></html>
